import 'package:flutter/material.dart';

class SecretWord {
  final String word;
  final String hint;

  const SecretWord({
    required this.word,
    required this.hint,
  });
}

class Category {
  final String id;
  final String name;
  final IconData icon;
  final List<SecretWord> secretWords;
  final bool isSelected;

  const Category({
    required this.id,
    required this.name,
    required this.icon,
    required this.secretWords,
    this.isSelected = false,
  });

  List<String> get words => secretWords.map((sw) => sw.word).toList();

  Category copyWith({
    String? id,
    String? name,
    IconData? icon,
    List<SecretWord>? secretWords,
    bool? isSelected,
  }) {
    return Category(
      id: id ?? this.id,
      name: name ?? this.name,
      icon: icon ?? this.icon,
      secretWords: secretWords ?? this.secretWords,
      isSelected: isSelected ?? this.isSelected,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;
}

/// categorias
class PredefinedCategories {
  static const List<Category> all = [
    Category(
      id: 'food',
      name: 'Comida',
      icon: Icons.restaurant,
      secretWords: [
        SecretWord(word: 'Pizza', hint: 'Italia'),
        SecretWord(word: 'Sushi', hint: 'Japón'),
        SecretWord(word: 'Hamburguesa', hint: 'Estados Unidos'),
        SecretWord(word: 'Tacos', hint: 'México'),
        SecretWord(word: 'Paella', hint: 'España'),
        SecretWord(word: 'Pasta', hint: 'Fideos'),
        SecretWord(word: 'Ensalada', hint: 'Vegetales'),
        SecretWord(word: 'Helado', hint: 'Frío'),
        SecretWord(word: 'Chocolate', hint: 'Cacao'),
        SecretWord(word: 'Churros', hint: 'Canela'),
        SecretWord(word: 'Empanada', hint: 'Relleno'),
        SecretWord(word: 'Ceviche', hint: 'Limón'),
        SecretWord(word: 'Ramen', hint: 'Caldo'),
        SecretWord(word: 'Curry', hint: 'Especias'),
        SecretWord(word: 'Croissant', hint: 'Francia'),
        SecretWord(word: 'Lasagna', hint: 'Capas'),
        SecretWord(word: 'Hot Dog', hint: 'Salchicha'),
        SecretWord(word: 'Arepa', hint: 'Maíz'),
        SecretWord(word: 'Pad Thai', hint: 'Tailandia'),
        SecretWord(word: 'Burrito', hint: 'Tortilla'),
        SecretWord(word: 'Falafel', hint: 'Garbanzos'),
        SecretWord(word: 'Pho', hint: 'Vietnam'),
        SecretWord(word: 'Tamales', hint: 'Hoja'),
        SecretWord(word: 'Kebab', hint: 'Brocheta'),
        SecretWord(word: 'Gyoza', hint: 'Dumpling'),
        SecretWord(word: 'Risotto', hint: 'Arroz'),
        SecretWord(word: 'Waffles', hint: 'Jarabe'),
        SecretWord(word: 'Pancakes', hint: 'Desayuno'),
        SecretWord(word: 'Bagel', hint: 'Dona salada'),
        SecretWord(word: 'Brownie', hint: 'Chocolate'),
        SecretWord(word: 'Tiramisu', hint: 'Café'),
        SecretWord(word: 'Cheesecake', hint: 'Queso'),
        SecretWord(word: 'Donut', hint: 'Glaseado'),
        SecretWord(word: 'Muffin', hint: 'Arándano'),
        SecretWord(word: 'Nachos', hint: 'Chips'),
        SecretWord(word: 'Quesadilla', hint: 'Queso derretido'),
        SecretWord(word: 'Croquetas', hint: 'Fritas'),
        SecretWord(word: 'Tortilla', hint: 'Huevo'),
        SecretWord(word: 'Gazpacho', hint: 'Frío'),
        SecretWord(word: 'Hummus', hint: 'Garbanzo'),
        SecretWord(word: 'Guacamole', hint: 'Aguacate'),
        SecretWord(word: 'Salsa', hint: 'Tomate'),
        SecretWord(word: 'Baguette', hint: 'Pan largo'),
        SecretWord(word: 'Pretzel', hint: 'Sal'),
        SecretWord(word: 'Crepe', hint: 'Delgado'),
        SecretWord(word: 'Macaron', hint: 'París'),
        SecretWord(word: 'Eclaire', hint: 'Crema'),
        SecretWord(word: 'Baklava', hint: 'Miel'),
        SecretWord(word: 'Kimchi', hint: 'Fermentado'),
        SecretWord(word: 'Bibimbap', hint: 'Cuenco'),
        SecretWord(word: 'Pa amb tomàquet', hint: 'Cataluña'),
        SecretWord(word: 'Milanesa', hint: 'Empanizado'),
        SecretWord(word: 'Feijoada', hint: 'Brasil'),
        SecretWord(word: 'Poutine', hint: 'Canadá'),
        SecretWord(word: 'Shawarma', hint: 'Asador vertical'),
        SecretWord(word: 'Açaí bowl', hint: 'Fruta morada'),
        SecretWord(word: 'Canelones', hint: 'Rellenos'),
        SecretWord(word: 'Sancocho', hint: 'Caldo espeso'),
        SecretWord(word: 'Mole', hint: 'Chocolate salado'),
        SecretWord(word: 'Panettone', hint: 'Navidad'),
      ],
    ),
    Category(
      id: 'places',
      name: 'Lugares',
      icon: Icons.place,
      secretWords: [
        SecretWord(word: 'Playa', hint: 'Arena'),
        SecretWord(word: 'Montaña', hint: 'Altura'),
        SecretWord(word: 'Museo', hint: 'Arte'),
        SecretWord(word: 'Parque', hint: 'Árboles'),
        SecretWord(word: 'Cine', hint: 'Películas'),
        SecretWord(word: 'Hospital', hint: 'Doctores'),
        SecretWord(word: 'Aeropuerto', hint: 'Aviones'),
        SecretWord(word: 'Biblioteca', hint: 'Libros'),
        SecretWord(word: 'Estadio', hint: 'Deportes'),
        SecretWord(word: 'Centro comercial', hint: 'Tiendas'),
        SecretWord(word: 'Restaurante', hint: 'Menú'),
        SecretWord(word: 'Iglesia', hint: 'Religión'),
        SecretWord(word: 'Universidad', hint: 'Estudiantes'),
        SecretWord(word: 'Zoológico', hint: 'Animales'),
        SecretWord(word: 'Gimnasio', hint: 'Ejercicio'),
        SecretWord(word: 'Cascada', hint: 'Agua'),
        SecretWord(word: 'Desierto', hint: 'Calor'),
        SecretWord(word: 'Selva', hint: 'Tropical'),
        SecretWord(word: 'Volcán', hint: 'Lava'),
        SecretWord(word: 'Cueva', hint: 'Oscuridad'),
        SecretWord(word: 'Lago', hint: 'Agua dulce'),
        SecretWord(word: 'Río', hint: 'Corriente'),
        SecretWord(word: 'Isla', hint: 'Rodeada'),
        SecretWord(word: 'Bosque', hint: 'Madera'),
        SecretWord(word: 'Valle', hint: 'Entre montañas'),
        SecretWord(word: 'Plaza', hint: 'Centro'),
        SecretWord(word: 'Mercado', hint: 'Vendedores'),
        SecretWord(word: 'Teatro', hint: 'Escenario'),
        SecretWord(word: 'Casino', hint: 'Juegos'),
        SecretWord(word: 'Hotel', hint: 'Hospedaje'),
        SecretWord(word: 'Banco', hint: 'Dinero'),
        SecretWord(word: 'Oficina', hint: 'Trabajo'),
        SecretWord(word: 'Fábrica', hint: 'Producción'),
        SecretWord(word: 'Puerto', hint: 'Barcos'),
        SecretWord(word: 'Estación de tren', hint: 'Vías'),
        SecretWord(word: 'Supermercado', hint: 'Carrito'),
        SecretWord(word: 'Farmacia', hint: 'Medicamentos'),
        SecretWord(word: 'Escuela', hint: 'Clases'),
        SecretWord(word: 'Cafetería', hint: 'Capuchino'),
        SecretWord(word: 'Bar', hint: 'Bebidas'),
        SecretWord(word: 'Discoteca', hint: 'Bailar'),
        SecretWord(word: 'Acuario', hint: 'Peces'),
        SecretWord(word: 'Planetario', hint: 'Estrellas'),
        SecretWord(word: 'Torre', hint: 'Alto'),
        SecretWord(word: 'Castillo', hint: 'Medieval'),
        SecretWord(word: 'Puente', hint: 'Cruzar'),
        SecretWord(word: 'Túnel', hint: 'Subterráneo'),
        SecretWord(word: 'Mirador', hint: 'Vista'),
        SecretWord(word: 'Granja', hint: 'Animales'),
        SecretWord(word: 'Jardín', hint: 'Flores'),
        SecretWord(word: 'Observatorio', hint: 'Telescopio'),
        SecretWord(word: 'Refugio', hint: 'Montaña'),
        SecretWord(word: 'Glaciar', hint: 'Hielo eterno'),
        SecretWord(word: 'Cancha', hint: 'Partido'),
        SecretWord(word: 'Viñedo', hint: 'Uvas'),
        SecretWord(word: 'Templo', hint: 'Ritual'),
        SecretWord(word: 'Búnker', hint: 'Subsuelo'),
        SecretWord(word: 'Faro', hint: 'Luz costera'),
        SecretWord(word: 'Estación de metro', hint: 'Subte'),
        SecretWord(word: 'Parque temático', hint: 'Atracciones'),
      ],
    ),
    Category(
      id: 'animals',
      name: 'Animales',
      icon: Icons.pets,
      secretWords: [
        SecretWord(word: 'Elefante', hint: 'Trompa'),
        SecretWord(word: 'León', hint: 'Melena'),
        SecretWord(word: 'Delfín', hint: 'Océano'),
        SecretWord(word: 'Águila', hint: 'Volar'),
        SecretWord(word: 'Serpiente', hint: 'Reptil'),
        SecretWord(word: 'Pingüino', hint: 'Antártida'),
        SecretWord(word: 'Koala', hint: 'Australia'),
        SecretWord(word: 'Jirafa', hint: 'Cuello'),
        SecretWord(word: 'Canguro', hint: 'Saltar'),
        SecretWord(word: 'Pulpo', hint: 'Tentáculos'),
        SecretWord(word: 'Tigre', hint: 'Rayas'),
        SecretWord(word: 'Oso', hint: 'Hibernar'),
        SecretWord(word: 'Lobo', hint: 'Manada'),
        SecretWord(word: 'Ballena', hint: 'Gigante'),
        SecretWord(word: 'Cocodrilo', hint: 'Pantano'),
        SecretWord(word: 'Rinoceronte', hint: 'Cuerno'),
        SecretWord(word: 'Hipopótamo', hint: 'Agua'),
        SecretWord(word: 'Zebra', hint: 'Blanco y negro'),
        SecretWord(word: 'Gorila', hint: 'Primate'),
        SecretWord(word: 'Panda', hint: 'Bambú'),
        SecretWord(word: 'Guepardo', hint: 'Velocidad'),
        SecretWord(word: 'Búho', hint: 'Nocturno'),
        SecretWord(word: 'Flamenco', hint: 'Rosa'),
        SecretWord(word: 'Pavo real', hint: 'Plumas'),
        SecretWord(word: 'Loro', hint: 'Hablar'),
        SecretWord(word: 'Colibrí', hint: 'Pequeño'),
        SecretWord(word: 'Murciélago', hint: 'Ultrasonido'),
        SecretWord(word: 'Conejo', hint: 'Orejas'),
        SecretWord(word: 'Zorro', hint: 'Astuto'),
        SecretWord(word: 'Ardilla', hint: 'Nueces'),
        SecretWord(word: 'Mapache', hint: 'Antifaz'),
        SecretWord(word: 'Castor', hint: 'Dique'),
        SecretWord(word: 'Nutria', hint: 'Río'),
        SecretWord(word: 'Foca', hint: 'Hielo'),
        SecretWord(word: 'Morsa', hint: 'Colmillos'),
        SecretWord(word: 'Tiburón', hint: 'Aleta'),
        SecretWord(word: 'Medusa', hint: 'Gelatina'),
        SecretWord(word: 'Estrella de mar', hint: 'Cinco puntas'),
        SecretWord(word: 'Cangrejo', hint: 'Pinzas'),
        SecretWord(word: 'Camello', hint: 'Joroba'),
        SecretWord(word: 'Llama', hint: 'Andes'),
        SecretWord(word: 'Alpaca', hint: 'Lana'),
        SecretWord(word: 'Búfalo', hint: 'Rebaño'),
        SecretWord(word: 'Bisonte', hint: 'América'),
        SecretWord(word: 'Avestruz', hint: 'Correr'),
        SecretWord(word: 'Emú', hint: 'Australia'),
        SecretWord(word: 'Cebra', hint: 'Líneas'),
        SecretWord(word: 'Leopardo', hint: 'Manchas'),
        SecretWord(word: 'Pantera', hint: 'Negro'),
        SecretWord(word: 'Hormiga', hint: 'Colonia'),
        SecretWord(word: 'Perezoso', hint: 'Lento'),
        SecretWord(word: 'Erizo', hint: 'Pinchos'),
        SecretWord(word: 'Caballito de mar', hint: 'Océano'),
        SecretWord(word: 'Caracol', hint: 'Concha'),
        SecretWord(word: 'Orca', hint: 'Blanco y negro'),
        SecretWord(word: 'Jaguar', hint: 'Selva'),
        SecretWord(word: 'Venado', hint: 'Astas'),
        SecretWord(word: 'Topo', hint: 'Bajo tierra'),
        SecretWord(word: 'Gavilán', hint: 'Rapaz'),
        SecretWord(word: 'Cisne', hint: 'Lago'),
      ],
    ),
    Category(
      id: 'technology',
      name: 'Tecnología',
      icon: Icons.computer,
      secretWords: [
        SecretWord(word: 'Smartphone', hint: 'Llamadas'),
        SecretWord(word: 'Laptop', hint: 'Portátil'),
        SecretWord(word: 'Drone', hint: 'Volar'),
        SecretWord(word: 'Robot', hint: 'Automatización'),
        SecretWord(word: 'Internet', hint: 'Conexión'),
        SecretWord(word: 'Bluetooth', hint: 'Inalámbrico'),
        SecretWord(word: 'WiFi', hint: 'Red'),
        SecretWord(word: 'Impresora', hint: 'Papel'),
        SecretWord(word: 'Videojuego', hint: 'Consola'),
        SecretWord(word: 'Smartwatch', hint: 'Muñeca'),
        SecretWord(word: 'Tablet', hint: 'Táctil'),
        SecretWord(word: 'Auriculares', hint: 'Música'),
        SecretWord(word: 'Cámara', hint: 'Fotos'),
        SecretWord(word: 'USB', hint: 'Memoria'),
        SecretWord(word: 'Inteligencia Artificial', hint: 'Aprendizaje'),
        SecretWord(word: 'Realidad Virtual', hint: 'Gafas'),
        SecretWord(word: 'Impresora 3D', hint: 'Tridimensional'),
        SecretWord(word: 'Teclado', hint: 'Escribir'),
        SecretWord(word: 'Mouse', hint: 'Clic'),
        SecretWord(word: 'Monitor', hint: 'Pantalla'),
        SecretWord(word: 'Altavoz', hint: 'Sonido'),
        SecretWord(word: 'Micrófono', hint: 'Voz'),
        SecretWord(word: 'Disco duro', hint: 'Almacenamiento'),
        SecretWord(word: 'Router', hint: 'Conexión'),
        SecretWord(word: 'Servidor', hint: 'Datos'),
        SecretWord(word: 'Consola', hint: 'Videojuegos'),
        SecretWord(word: 'Procesador', hint: 'CPU'),
        SecretWord(word: 'Tarjeta gráfica', hint: 'GPU'),
        SecretWord(word: 'RAM', hint: 'Memoria'),
        SecretWord(word: 'SSD', hint: 'Sólido'),
        SecretWord(word: 'Webcam', hint: 'Video'),
        SecretWord(word: 'Escáner', hint: 'Digitalizar'),
        SecretWord(word: 'Proyector', hint: 'Proyección'),
        SecretWord(word: 'Control remoto', hint: 'Distancia'),
        SecretWord(word: 'GPS', hint: 'Ubicación'),
        SecretWord(word: 'Satélite', hint: 'Órbita'),
        SecretWord(word: 'Fibra óptica', hint: 'Luz'),
        SecretWord(word: 'Blockchain', hint: 'Cadena'),
        SecretWord(word: 'Cloud', hint: 'Nube'),
        SecretWord(word: 'Software', hint: 'Programa'),
        SecretWord(word: 'Hardware', hint: 'Físico'),
        SecretWord(word: 'App', hint: 'Aplicación'),
        SecretWord(word: 'QR', hint: 'Código'),
        SecretWord(word: 'NFC', hint: 'Pago'),
        SecretWord(word: 'LED', hint: 'Luz'),
        SecretWord(word: 'OLED', hint: 'Orgánico'),
        SecretWord(word: 'Touchpad', hint: 'Táctil'),
        SecretWord(word: 'Joystick', hint: 'Palanca'),
        SecretWord(word: 'Módem', hint: 'Modulador'),
        SecretWord(word: 'Firewall', hint: 'Protección'),
        SecretWord(word: 'Domótica', hint: 'Casa inteligente'),
        SecretWord(word: 'Wearable', hint: 'Accesorio tech'),
        SecretWord(word: 'Powerbank', hint: 'Batería externa'),
        SecretWord(word: 'NAS', hint: 'Almacenamiento en red'),
        SecretWord(word: 'Kernel', hint: 'Núcleo del sistema'),
        SecretWord(word: 'API', hint: 'Integración'),
        SecretWord(word: 'Machine Learning', hint: 'Modelos'),
        SecretWord(word: 'Prompt', hint: 'Instrucción'),
        SecretWord(word: 'VPN', hint: 'Conexión privada'),
        SecretWord(word: 'Captcha', hint: 'No soy un robot'),
      ],
    ),
    Category(
      id: 'movies',
      name: 'Cine',
      icon: Icons.movie,
      secretWords: [
        SecretWord(word: 'Star Wars', hint: 'Espacio'),
        SecretWord(word: 'Titanic', hint: 'Barco'),
        SecretWord(word: 'Avatar', hint: 'Azul'),
        SecretWord(word: 'Matrix', hint: 'Píldora'),
        SecretWord(word: 'Jurassic Park', hint: 'Dinosaurios'),
        SecretWord(word: 'El Padrino', hint: 'Mafia'),
        SecretWord(word: 'Toy Story', hint: 'Juguetes'),
        SecretWord(word: 'Batman', hint: 'Murciélago'),
        SecretWord(word: 'Harry Potter', hint: 'Magia'),
        SecretWord(word: 'Frozen', hint: 'Hielo'),
        SecretWord(word: 'Inception', hint: 'Sueños'),
        SecretWord(word: 'Gladiator', hint: 'Roma'),
        SecretWord(word: 'Avengers', hint: 'Superhéroes'),
        SecretWord(word: 'Forrest Gump', hint: 'Correr'),
        SecretWord(word: 'El Rey León', hint: 'Simba'),
        SecretWord(word: 'Pulp Fiction', hint: 'Tarantino'),
        SecretWord(word: 'Spider-Man', hint: 'Araña'),
        SecretWord(word: 'Iron Man', hint: 'Armadura'),
        SecretWord(word: 'Shrek', hint: 'Ogro'),
        SecretWord(word: 'Buscando a Nemo', hint: 'Pez'),
        SecretWord(word: 'Los Increíbles', hint: 'Familia'),
        SecretWord(word: 'Coco', hint: 'México'),
        SecretWord(word: 'Moana', hint: 'Océano'),
        SecretWord(word: 'Encanto', hint: 'Colombia'),
        SecretWord(word: 'Interestelar', hint: 'Tiempo'),
        SecretWord(word: 'El Señor de los Anillos', hint: 'Anillo'),
        SecretWord(word: 'Piratas del Caribe', hint: 'Jack Sparrow'),
        SecretWord(word: 'Transformers', hint: 'Robots'),
        SecretWord(word: 'Fast & Furious', hint: 'Carreras'),
        SecretWord(word: 'Misión Imposible', hint: 'Espía'),
        SecretWord(word: 'James Bond', hint: '007'),
        SecretWord(word: 'Rocky', hint: 'Boxeador'),
        SecretWord(word: 'Terminator', hint: 'Cyborg'),
        SecretWord(word: 'Alien', hint: 'Espacio'),
        SecretWord(word: 'Depredador', hint: 'Camuflaje'),
        SecretWord(word: 'Volver al Futuro', hint: 'DeLorean'),
        SecretWord(word: 'Indiana Jones', hint: 'Arqueólogo'),
        SecretWord(word: 'King Kong', hint: 'Gorila'),
        SecretWord(word: 'Godzilla', hint: 'Monstruo'),
        SecretWord(word: 'Mad Max', hint: 'Desierto'),
        SecretWord(word: 'Joker', hint: 'Payaso'),
        SecretWord(word: 'Black Panther', hint: 'Wakanda'),
        SecretWord(word: 'Deadpool', hint: 'Rojo'),
        SecretWord(word: 'Crepúsculo', hint: 'Vampiro'),
        SecretWord(word: 'Los Juegos del Hambre', hint: 'Arena'),
        SecretWord(word: 'Divergente', hint: 'Facciones'),
        SecretWord(word: 'El Hobbit', hint: 'Dragón'),
        SecretWord(word: 'Crónicas de Narnia', hint: 'Armario'),
        SecretWord(word: 'Percy Jackson', hint: 'Semidiós'),
        SecretWord(word: 'Maze Runner', hint: 'Laberinto'),
        SecretWord(word: 'Top Gun', hint: 'Pilotos'),
        SecretWord(word: 'Whiplash', hint: 'Batería'),
        SecretWord(word: 'La La Land', hint: 'Musical'),
        SecretWord(word: 'Parasite', hint: 'Corea'),
        SecretWord(word: 'Oppenheimer', hint: 'Bomba'),
        SecretWord(word: 'Barbie', hint: 'Rosa'),
        SecretWord(word: 'Dune', hint: 'Especia'),
        SecretWord(word: 'Soul', hint: 'Jazz'),
        SecretWord(word: 'Inside Out', hint: 'Emociones'),
        SecretWord(word: 'Wall-E', hint: 'Robot'),
      ],
    ),
    Category(
      id: 'sports',
      name: 'Deportes',
      icon: Icons.sports_soccer,
      secretWords: [
        SecretWord(word: 'Fútbol', hint: 'Gol'),
        SecretWord(word: 'Baloncesto', hint: 'Canasta'),
        SecretWord(word: 'Tenis', hint: 'Raqueta'),
        SecretWord(word: 'Natación', hint: 'Piscina'),
        SecretWord(word: 'Béisbol', hint: 'Bate'),
        SecretWord(word: 'Golf', hint: 'Hoyo'),
        SecretWord(word: 'Boxeo', hint: 'Guantes'),
        SecretWord(word: 'Ciclismo', hint: 'Bicicleta'),
        SecretWord(word: 'Esquí', hint: 'Nieve'),
        SecretWord(word: 'Surf', hint: 'Olas'),
        SecretWord(word: 'Volleyball', hint: 'Red'),
        SecretWord(word: 'Rugby', hint: 'Tacleo'),
        SecretWord(word: 'Hockey', hint: 'Puck'),
        SecretWord(word: 'Atletismo', hint: 'Carrera'),
        SecretWord(word: 'Gimnasia', hint: 'Acrobacia'),
        SecretWord(word: 'Karate', hint: 'Artes marciales'),
        SecretWord(word: 'Judo', hint: 'Tatami'),
        SecretWord(word: 'Taekwondo', hint: 'Patadas'),
        SecretWord(word: 'Esgrima', hint: 'Espada'),
        SecretWord(word: 'Ping Pong', hint: 'Mesa'),
        SecretWord(word: 'Bádminton', hint: 'Volante'),
        SecretWord(word: 'Skateboarding', hint: 'Tabla'),
        SecretWord(word: 'Snowboard', hint: 'Tabla de nieve'),
        SecretWord(word: 'Escalada', hint: 'Muro'),
        SecretWord(word: 'Parkour', hint: 'Obstáculos'),
        SecretWord(word: 'Paracaidismo', hint: 'Saltar'),
        SecretWord(word: 'Buceo', hint: 'Submarino'),
        SecretWord(word: 'Vela', hint: 'Barco'),
        SecretWord(word: 'Remo', hint: 'Paleta'),
        SecretWord(word: 'Kayak', hint: 'Canoa'),
        SecretWord(word: 'Polo', hint: 'Caballo'),
        SecretWord(word: 'Equitación', hint: 'Montar'),
        SecretWord(word: 'Motocross', hint: 'Moto'),
        SecretWord(word: 'Rally', hint: 'Tierra'),
        SecretWord(word: 'Fórmula 1', hint: 'Velocidad'),
        SecretWord(word: 'MMA', hint: 'Jaula'),
        SecretWord(word: 'Lucha libre', hint: 'Ring'),
        SecretWord(word: 'Halterofilia', hint: 'Pesas'),
        SecretWord(word: 'Crossfit', hint: 'Intensidad'),
        SecretWord(word: 'Yoga', hint: 'Flexibilidad'),
        SecretWord(word: 'Pilates', hint: 'Core'),
        SecretWord(word: 'Zumba', hint: 'Baile'),
        SecretWord(word: 'Aeróbicos', hint: 'Cardio'),
        SecretWord(word: 'Maratón', hint: '42 km'),
        SecretWord(word: 'Triatlón', hint: 'Tres deportes'),
        SecretWord(word: 'Pentatlón', hint: 'Cinco deportes'),
        SecretWord(word: 'Polo acuático', hint: 'Agua'),
        SecretWord(word: 'Waterpolo', hint: 'Pelota'),
        SecretWord(word: 'Cricket', hint: 'Inglaterra'),
        SecretWord(word: 'Lacrosse', hint: 'Red'),
        SecretWord(word: 'Pádel', hint: 'Paredes'),
        SecretWord(word: 'Pickleball', hint: 'Paleta'),
        SecretWord(word: 'Ajedrez', hint: 'Jaque mate'),
        SecretWord(word: 'Dardos', hint: 'Blanco'),
        SecretWord(word: 'Futsal', hint: 'Cancha chica'),
        SecretWord(word: 'Handball', hint: 'Balón mano'),
        SecretWord(word: 'Patinaje artístico', hint: 'Hielo'),
        SecretWord(word: 'Patinaje de velocidad', hint: 'Cronómetro'),
        SecretWord(word: 'Breakdance', hint: 'Olimpiadas urbanas'),
        SecretWord(word: 'Bolos', hint: 'Pinos'),
      ],
    ),
    Category(
      id: 'professions',
      name: 'Profesiones',
      icon: Icons.work,
      secretWords: [
        SecretWord(word: 'Doctor', hint: 'Salud'),
        SecretWord(word: 'Abogado', hint: 'Leyes'),
        SecretWord(word: 'Chef', hint: 'Cocina'),
        SecretWord(word: 'Piloto', hint: 'Avión'),
        SecretWord(word: 'Arquitecto', hint: 'Edificios'),
        SecretWord(word: 'Bombero', hint: 'Fuego'),
        SecretWord(word: 'Policía', hint: 'Seguridad'),
        SecretWord(word: 'Maestro', hint: 'Escuela'),
        SecretWord(word: 'Ingeniero', hint: 'Construcción'),
        SecretWord(word: 'Músico', hint: 'Instrumento'),
        SecretWord(word: 'Actor', hint: 'Teatro'),
        SecretWord(word: 'Científico', hint: 'Laboratorio'),
        SecretWord(word: 'Periodista', hint: 'Noticias'),
        SecretWord(word: 'Veterinario', hint: 'Mascotas'),
        SecretWord(word: 'Diseñador', hint: 'Creatividad'),
        SecretWord(word: 'Programador', hint: 'Código'),
        SecretWord(word: 'Dentista', hint: 'Dientes'),
        SecretWord(word: 'Enfermera', hint: 'Hospital'),
        SecretWord(word: 'Psicólogo', hint: 'Mente'),
        SecretWord(word: 'Contador', hint: 'Números'),
        SecretWord(word: 'Economista', hint: 'Finanzas'),
        SecretWord(word: 'Banquero', hint: 'Banco'),
        SecretWord(word: 'Empresario', hint: 'Negocio'),
        SecretWord(word: 'Gerente', hint: 'Administrar'),
        SecretWord(word: 'Secretaria', hint: 'Oficina'),
        SecretWord(word: 'Recepcionista', hint: 'Entrada'),
        SecretWord(word: 'Electricista', hint: 'Cables'),
        SecretWord(word: 'Plomero', hint: 'Tuberías'),
        SecretWord(word: 'Carpintero', hint: 'Madera'),
        SecretWord(word: 'Mecánico', hint: 'Motor'),
        SecretWord(word: 'Pintor', hint: 'Brocha'),
        SecretWord(word: 'Fotógrafo', hint: 'Cámara'),
        SecretWord(word: 'Camarógrafo', hint: 'Video'),
        SecretWord(word: 'Director', hint: 'Película'),
        SecretWord(word: 'Guionista', hint: 'Escribir'),
        SecretWord(word: 'Escritor', hint: 'Libro'),
        SecretWord(word: 'Poeta', hint: 'Versos'),
        SecretWord(word: 'Traductor', hint: 'Idiomas'),
        SecretWord(word: 'Intérprete', hint: 'Simultáneo'),
        SecretWord(word: 'Bibliotecario', hint: 'Libros'),
        SecretWord(word: 'Arqueólogo', hint: 'Excavación'),
        SecretWord(word: 'Biólogo', hint: 'Vida'),
        SecretWord(word: 'Químico', hint: 'Elementos'),
        SecretWord(word: 'Físico', hint: 'Partículas'),
        SecretWord(word: 'Astrónomo', hint: 'Estrellas'),
        SecretWord(word: 'Geólogo', hint: 'Rocas'),
        SecretWord(word: 'Meteorólogo', hint: 'Clima'),
        SecretWord(word: 'Agricultor', hint: 'Cultivo'),
        SecretWord(word: 'Ganadero', hint: 'Ganado'),
        SecretWord(word: 'Pescador', hint: 'Red'),
        SecretWord(word: 'Community Manager', hint: 'Redes sociales'),
        SecretWord(word: 'UX Designer', hint: 'Experiencia de usuario'),
        SecretWord(word: 'Data Analyst', hint: 'Dashboard'),
        SecretWord(word: 'DevOps', hint: 'Despliegues'),
        SecretWord(word: 'Paramédico', hint: 'Emergencia'),
        SecretWord(word: 'Terapeuta', hint: 'Sesiones'),
        SecretWord(word: 'Locutor', hint: 'Radio'),
        SecretWord(word: 'Tatuador', hint: 'Tinta'),
        SecretWord(word: 'Sommelier', hint: 'Vino'),
        SecretWord(word: 'Barista', hint: 'Espresso'),
      ],
    ),
    Category(
      id: 'countries',
      name: 'Países',
      icon: Icons.flag,
      secretWords: [
        SecretWord(word: 'España', hint: 'Flamenco'),
        SecretWord(word: 'México', hint: 'Mariachi'),
        SecretWord(word: 'Argentina', hint: 'Tango'),
        SecretWord(word: 'Japón', hint: 'Samurái'),
        SecretWord(word: 'Francia', hint: 'Torre Eiffel'),
        SecretWord(word: 'Italia', hint: 'Coliseo'),
        SecretWord(word: 'Brasil', hint: 'Samba'),
        SecretWord(word: 'Alemania', hint: 'Cerveza'),
        SecretWord(word: 'Australia', hint: 'Canguro'),
        SecretWord(word: 'Canadá', hint: 'Maple'),
        SecretWord(word: 'Egipto', hint: 'Pirámides'),
        SecretWord(word: 'India', hint: 'Bollywood'),
        SecretWord(word: 'Rusia', hint: 'Kremlin'),
        SecretWord(word: 'Sudáfrica', hint: 'Safari'),
        SecretWord(word: 'Corea del Sur', hint: 'K-Pop'),
        SecretWord(word: 'China', hint: 'Muralla'),
        SecretWord(word: 'Estados Unidos', hint: 'Estatua'),
        SecretWord(word: 'Inglaterra', hint: 'Big Ben'),
        SecretWord(word: 'Perú', hint: 'Machu Picchu'),
        SecretWord(word: 'Colombia', hint: 'Café'),
        SecretWord(word: 'Chile', hint: 'Largo'),
        SecretWord(word: 'Venezuela', hint: 'Petróleo'),
        SecretWord(word: 'Ecuador', hint: 'Mitad'),
        SecretWord(word: 'Cuba', hint: 'Habano'),
        SecretWord(word: 'Grecia', hint: 'Partenón'),
        SecretWord(word: 'Turquía', hint: 'Mezquita'),
        SecretWord(word: 'Tailandia', hint: 'Elefante'),
        SecretWord(word: 'Vietnam', hint: 'Hanoi'),
        SecretWord(word: 'Indonesia', hint: 'Islas'),
        SecretWord(word: 'Filipinas', hint: 'Archipiélago'),
        SecretWord(word: 'Singapur', hint: 'Ciudad'),
        SecretWord(word: 'Malasia', hint: 'Torres'),
        SecretWord(word: 'Nueva Zelanda', hint: 'Kiwi'),
        SecretWord(word: 'Irlanda', hint: 'Trébol'),
        SecretWord(word: 'Escocia', hint: 'Gaita'),
        SecretWord(word: 'Noruega', hint: 'Fiordo'),
        SecretWord(word: 'Suecia', hint: 'IKEA'),
        SecretWord(word: 'Finlandia', hint: 'Nokia'),
        SecretWord(word: 'Dinamarca', hint: 'Viking'),
        SecretWord(word: 'Holanda', hint: 'Tulipán'),
        SecretWord(word: 'Bélgica', hint: 'Chocolate'),
        SecretWord(word: 'Suiza', hint: 'Reloj'),
        SecretWord(word: 'Austria', hint: 'Mozart'),
        SecretWord(word: 'Portugal', hint: 'Fado'),
        SecretWord(word: 'Polonia', hint: 'Varsovia'),
        SecretWord(word: 'Marruecos', hint: 'Marrakech'),
        SecretWord(word: 'Kenia', hint: 'Safari'),
        SecretWord(word: 'Nigeria', hint: 'Lagos'),
        SecretWord(word: 'Jamaica', hint: 'Reggae'),
        SecretWord(word: 'Costa Rica', hint: 'Pura vida'),
        SecretWord(word: 'Uruguay', hint: 'Mate'),
        SecretWord(word: 'Bolivia', hint: 'Altiplano'),
        SecretWord(word: 'Paraguay', hint: 'Guaraní'),
        SecretWord(word: 'Panamá', hint: 'Canal'),
        SecretWord(word: 'República Dominicana', hint: 'Caribe'),
        SecretWord(word: 'El Salvador', hint: 'Pupusas'),
        SecretWord(word: 'Guatemala', hint: 'Quetzal'),
        SecretWord(word: 'Islandia', hint: 'Géiser'),
        SecretWord(word: 'Ucrania', hint: 'Kyiv'),
        SecretWord(word: 'Arabia Saudita', hint: 'Desierto'),
      ],
    ),
    Category(
      id: 'anime',
      name: 'Anime',
      icon: Icons.animation,
      secretWords: [
        SecretWord(word: 'Naruto', hint: 'Ninja'),
        SecretWord(word: 'Dragon Ball', hint: 'Goku'),
        SecretWord(word: 'One Piece', hint: 'Piratas'),
        SecretWord(word: 'Death Note', hint: 'Libreta'),
        SecretWord(word: 'Attack on Titan', hint: 'Murallas'),
        SecretWord(word: 'Demon Slayer', hint: 'Espada'),
        SecretWord(word: 'My Hero Academia', hint: 'Quirk'),
        SecretWord(word: 'Pokémon', hint: 'Pikachu'),
        SecretWord(word: 'Tokyo Ghoul', hint: 'Máscara'),
        SecretWord(word: 'Fullmetal Alchemist', hint: 'Metal'),
        SecretWord(word: 'Sword Art Online', hint: 'Virtual'),
        SecretWord(word: 'Bleach', hint: 'Shinigami'),
        SecretWord(word: 'Hunter x Hunter', hint: 'Nen'),
        SecretWord(word: 'One Punch Man', hint: 'Calvo'),
        SecretWord(word: 'Jujutsu Kaisen', hint: 'Maldiciones'),
        SecretWord(word: 'Code Geass', hint: 'Geass'),
        SecretWord(word: 'Steins Gate', hint: 'Tiempo'),
        SecretWord(word: 'Cowboy Bebop', hint: 'Espacio'),
        SecretWord(word: 'Neon Genesis Evangelion', hint: 'Mecha'),
        SecretWord(word: 'Mob Psycho 100', hint: 'Poderes'),
        SecretWord(word: 'Spy x Family', hint: 'Espía'),
        SecretWord(word: 'Chainsaw Man', hint: 'Motosierra'),
        SecretWord(word: 'Violet Evergarden', hint: 'Cartas'),
        SecretWord(word: 'Your Name', hint: 'Cometa'),
        SecretWord(word: 'Spirited Away', hint: 'Baños'),
        SecretWord(word: 'Totoro', hint: 'Bosque'),
        SecretWord(word: 'Howls Moving Castle', hint: 'Castillo'),
        SecretWord(word: 'Fairy Tail', hint: 'Gremio'),
        SecretWord(word: 'Black Clover', hint: 'Grimorio'),
        SecretWord(word: 'Fire Force', hint: 'Fuego'),
        SecretWord(word: 'Dr. Stone', hint: 'Ciencia'),
        SecretWord(word: 'Haikyuu', hint: 'Volleyball'),
        SecretWord(word: 'Kuroko no Basket', hint: 'Baloncesto'),
        SecretWord(word: 'Slam Dunk', hint: 'Canasta'),
        SecretWord(word: 'Yu-Gi-Oh', hint: 'Cartas'),
        SecretWord(word: 'Digimon', hint: 'Digital'),
        SecretWord(word: 'InuYasha', hint: 'Medio demonio'),
        SecretWord(word: 'Ranma 1/2', hint: 'Transformación'),
        SecretWord(word: 'Sailor Moon', hint: 'Luna'),
        SecretWord(word: 'Sakura Card Captor', hint: 'Cartas'),
        SecretWord(word: 'Soul Eater', hint: 'Alma'),
        SecretWord(word: 'Parasyte', hint: 'Parásito'),
        SecretWord(word: 'Assassination Classroom', hint: 'Profesor'),
        SecretWord(word: 'The Promised Neverland', hint: 'Orfanato'),
        SecretWord(word: 'Made in Abyss', hint: 'Abismo'),
        SecretWord(word: 'Re:Zero', hint: 'Regresar'),
        SecretWord(word: 'Overlord', hint: 'Esqueleto'),
        SecretWord(word: 'Konosuba', hint: 'Diosa'),
        SecretWord(word: 'No Game No Life', hint: 'Juegos'),
        SecretWord(word: 'Tokyo Revengers', hint: 'Pandilla'),
        SecretWord(word: 'Blue Lock', hint: 'Delantero'),
        SecretWord(word: 'Solo Leveling', hint: 'Cazador'),
        SecretWord(word: 'Frieren', hint: 'Elfa'),
        SecretWord(word: 'Kaiju No. 8', hint: 'Monstruos'),
        SecretWord(word: 'Mashle', hint: 'Músculos y magia'),
        SecretWord(word: 'Dan Da Dan', hint: 'Paranormal'),
        SecretWord(word: 'Bocchi the Rock', hint: 'Banda'),
        SecretWord(word: 'Wind Breaker', hint: 'Pandillas'),
        SecretWord(word: 'Vinland Saga', hint: 'Vikingos'),
        SecretWord(word: 'Hell\'s Paradise', hint: 'Isla prohibida'),
      ],
    ),
    Category(
      id: 'brands',
      name: 'Marcas',
      icon: Icons.store,
      secretWords: [
        SecretWord(word: 'Apple', hint: 'Manzana'),
        SecretWord(word: 'Nike', hint: 'Swoosh'),
        SecretWord(word: 'Coca-Cola', hint: 'Refresco'),
        SecretWord(word: 'McDonald\'s', hint: 'Hamburguesa'),
        SecretWord(word: 'Samsung', hint: 'Galaxia'),
        SecretWord(word: 'Adidas', hint: 'Tres rayas'),
        SecretWord(word: 'Amazon', hint: 'Río'),
        SecretWord(word: 'Google', hint: 'Búsqueda'),
        SecretWord(word: 'Netflix', hint: 'Streaming'),
        SecretWord(word: 'Tesla', hint: 'Eléctrico'),
        SecretWord(word: 'Starbucks', hint: 'Café'),
        SecretWord(word: 'PlayStation', hint: 'Consola'),
        SecretWord(word: 'Ferrari', hint: 'Rojo'),
        SecretWord(word: 'Microsoft', hint: 'Windows'),
        SecretWord(word: 'Spotify', hint: 'Música'),
        SecretWord(word: 'Facebook', hint: 'Red social'),
        SecretWord(word: 'Instagram', hint: 'Fotos'),
        SecretWord(word: 'Twitter', hint: 'Pájaro'),
        SecretWord(word: 'YouTube', hint: 'Videos'),
        SecretWord(word: 'TikTok', hint: 'Cortos'),
        SecretWord(word: 'WhatsApp', hint: 'Mensajes'),
        SecretWord(word: 'Discord', hint: 'Chat'),
        SecretWord(word: 'Zoom', hint: 'Videoconferencia'),
        SecretWord(word: 'Uber', hint: 'Transporte'),
        SecretWord(word: 'Airbnb', hint: 'Alojamiento'),
        SecretWord(word: 'Pepsi', hint: 'Azul'),
        SecretWord(word: 'KFC', hint: 'Pollo'),
        SecretWord(word: 'Burger King', hint: 'Rey'),
        SecretWord(word: 'Subway', hint: 'Sándwich'),
        SecretWord(word: 'Pizza Hut', hint: 'Pizza'),
        SecretWord(word: 'Puma', hint: 'Felino'),
        SecretWord(word: 'Reebok', hint: 'Fitness'),
        SecretWord(word: 'Under Armour', hint: 'Armadura'),
        SecretWord(word: 'Converse', hint: 'Chuck Taylor'),
        SecretWord(word: 'Vans', hint: 'Skate'),
        SecretWord(word: 'Levi\'s', hint: 'Jeans'),
        SecretWord(word: 'Zara', hint: 'Moda'),
        SecretWord(word: 'H&M', hint: 'Ropa'),
        SecretWord(word: 'Gucci', hint: 'Lujo'),
        SecretWord(word: 'Louis Vuitton', hint: 'Bolso'),
        SecretWord(word: 'Chanel', hint: 'Perfume'),
        SecretWord(word: 'BMW', hint: 'Alemán'),
        SecretWord(word: 'Mercedes-Benz', hint: 'Estrella'),
        SecretWord(word: 'Audi', hint: 'Cuatro aros'),
        SecretWord(word: 'Toyota', hint: 'Confiable'),
        SecretWord(word: 'Honda', hint: 'Civic'),
        SecretWord(word: 'Ford', hint: 'Mustang'),
        SecretWord(word: 'Lamborghini', hint: 'Toro'),
        SecretWord(word: 'Porsche', hint: '911'),
        SecretWord(word: 'Xbox', hint: 'Microsoft'),
        SecretWord(word: 'OpenAI', hint: 'IA generativa'),
        SecretWord(word: 'NVIDIA', hint: 'Tarjetas gráficas'),
        SecretWord(word: 'AMD', hint: 'Ryzen'),
        SecretWord(word: 'Intel', hint: 'Procesadores'),
        SecretWord(word: 'ASUS', hint: 'ROG'),
        SecretWord(word: 'Lenovo', hint: 'ThinkPad'),
        SecretWord(word: 'Dell', hint: 'XPS'),
        SecretWord(word: 'Razer', hint: 'Gaming'),
        SecretWord(word: 'Canon', hint: 'Cámaras'),
        SecretWord(word: 'DJI', hint: 'Drones'),
      ],
    ),
    Category(
      id: 'music',
      name: 'Música',
      icon: Icons.music_note,
      secretWords: [
        SecretWord(word: 'Rock', hint: 'Guitarra eléctrica'),
        SecretWord(word: 'Reggaetón', hint: 'Perreo'),
        SecretWord(word: 'Salsa', hint: 'Clave'),
        SecretWord(word: 'Bachata', hint: 'Romántica'),
        SecretWord(word: 'Merengue', hint: 'República Dominicana'),
        SecretWord(word: 'Trap', hint: '808'),
        SecretWord(word: 'Jazz', hint: 'Improvisación'),
        SecretWord(word: 'Blues', hint: 'Doce compases'),
        SecretWord(word: 'Pop', hint: 'Comercial'),
        SecretWord(word: 'Electrónica', hint: 'DJ'),
        SecretWord(word: 'Cumbia', hint: 'Colombia'),
        SecretWord(word: 'Vallenato', hint: 'Acordeón'),
        SecretWord(word: 'Rap', hint: 'Rimas'),
        SecretWord(word: 'Hip Hop', hint: 'Cultura urbana'),
        SecretWord(word: 'House', hint: 'Club'),
        SecretWord(word: 'Techno', hint: 'BPM alto'),
        SecretWord(word: 'Piano', hint: 'Teclas'),
        SecretWord(word: 'Guitarra', hint: 'Cuerdas'),
        SecretWord(word: 'Batería', hint: 'Ritmo'),
        SecretWord(word: 'Bajo', hint: 'Graves'),
        SecretWord(word: 'Violin', hint: 'Arco'),
        SecretWord(word: 'Trompeta', hint: 'Viento metal'),
        SecretWord(word: 'Saxofón', hint: 'Jazz clásico'),
        SecretWord(word: 'Flauta', hint: 'Viento madera'),
      ],
    ),
  ];
}
